version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jobdb
      - SPRING_DATASOURCE_USERNAME=jobuser
      - SPRING_DATASOURCE_PASSWORD=jobpass

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jobdb
      - POSTGRES_USER=jobuser
      - POSTGRES_PASSWORD=jobpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 